# services:
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app:latest
    command: bash -c "bin/rails server -b 0.0.0.0 -p 3000"
    entrypoint: ./docker-compose-entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      - "RAILS_LOG_TO_STDOUT=true"
      - "RAILS_ENV=development"
      - "APP_URL_HOST=http://0.0.0.0:3000"
    depends_on:
      - postgres
